### ISSUE TITLE
no  aeffect relevant file

### ISSUE THREAD

**Issue by ghost** [Noahdw/MidiInter#2]
#include <SDK/portaudio.h>
#include <SDK/aeffect.h>
..................
...................

**Comment by Noahdw** [comment]
I added the relevant files but you will still need to build Portaudio debug and release versions and put them in ./Debug and ./Release folders . 

http://portaudio.com/docs/v19-doxydocs/compile_windows.html

Edit: removed them since you can't redistribute the SDK

**Comment by AnClark** [comment]
> I added the relevant files but you will still need to build Portaudio debug and release versions and put them in ./Debug and ./Release folders .
> 
> http://portaudio.com/docs/v19-doxydocs/compile_windows.html
> 
> Edit: removed them since you can't redistribute the SDK

It's better to inform this in your document.
