### ISSUE TITLE
You'd better release your Protobuf source file

### ISSUE THREAD

**Issue by AnClark** [Noahdw/MidiInter#5]
Hello @Noahdw ! I like this opensource DAW, and want to contribute to it. However, when I try to build, I encounter some severe problems.

One problem is that your **protoc-generated** C++ files are unavailable in newer versions of protobuf.

```
midiinter.pb.h
```

So would you love to release its source (`midiinter.proto`) instead of a built, machine-dependent one?

**Comment by Noahdw** [comment]
I added the file to the main folder. Feel free to contribute but ultimately this thing is a steaming pile of junk - a lot of bad design decisions compounded into each other which no amount of refactoring can save. A lot of the features are currently broken as well and it's unlikely that i'll ever really put enough effort into this to save it. Thanks for the interest though.

**Comment by AnClark** [comment]
OK! I'll sync.
