### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by alex-tee** [Noahdw/MidiInter#6]
Hi,

I'm not sure how much code you borrowed but apparently you are using code licensed under the GPL. The GPL says you must also license your code under the GPL (that's the whole point of it). Relicensing under the LGPL is a violation.

https://github.com/Noahdw/Strauss/blob/master/src/vst2audioplugin.cpp#L241
https://github.com/falkTX/dssi-vst/blob/master/dssi-vst-server.cpp

Just FYI

**Comment by Noahdw** [comment]
Thanks for letting me know. I probably didn't put enough research into licensing when I made this. I'll fix that. Impressive DAW you've built btw.

**Comment by alex-tee** [comment]
Thanks. There's another issue you should be aware of btw. Using the SDK for vst2 and the GPL is basically invalid because you can't directly include or link to proprietary software when using the GPL (I think this is also true for LGPL but I would double check). This is why most GPL'd projects with vst2 support use the reverse engineered vestige.h header instead of the SDK .
Thankfully the VST3 SDK is dual licensed under the GPL so it can be freely redistributed

**Comment by falkTX** [comment]
Note that vst2 sdk is not compatible with either GPL or LGPL, and the free vestige header is GPLv2+
So there is a bit of a situation regarding licensing here. You are mixing GPL code (dssi-vst) with non-free (vst2 sdk) and trying to pass it as LGPL.
Please fix this
