### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [Noahdw/MidiInter#9]
Hi there, 1st of all thanks for your cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [DAWs page](https://github.com/forart/HyMPS/blob/main/DAWs.md#--) \ [Generic subsection](https://github.com/forart/HyMPS/blob/main/DAWs.md#generic-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/Noahdw/Strauss/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/Noahdw/Strauss/?label=LICENSE)

Anyway you can easily set a "compliant" one through the GH's license wizard tool.

Last but not least, let us know how - in your opinion - we could improve categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by Noahdw** [comment]
sure, done

**Comment by MarcoRavich** [comment]
Thanks and happy holydays !
